site_name: UNT Talon3 High-Performance Computing Documentation

nav:
    - About: index.md
    
    - Details: details/details.md
    
    - User Guide:
        - Talon 3 User Guide: user_guide/user_guide.md
        - Getting Started: user_guide/getting_started.md
        
    - Terminal:
        - Commands: terminal/commands.md
        - SSH: terminal/ssh.md
        - Screen: terminal/screen.md
        
    - Python:
        - Info: python/python_info.md
        - Code Samples: python/code_samples.md
        - Tensorflow: python/tensorflow.md
        - PyTorch: python/pytorch.md
        
    - Jupyter:
        - Jupyter Notebook: jupyter/jupyter_notebook.md
        - Jupyter Hub: jupyter/jupyter_hub.md

    - PyCharm: pycharm/pycharm.md
    
    - R:
        - Info: r/r_info.md
        
    - Tutorials-Workshops: tutorials/tutorials.md

# Copyright footer
copyright: 'Copyright &copy; University of North Texas, University IT Services'

extra:
    manifest: manifest.webmanifest
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/UNT_RITS
        - icon: fontawesome/brands/github
          link: https://github.com/UNT-RITS

extra_css:
    - 'stylesheets/unibe.css'

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
    - abbr
    - def_list
    - tables
    - sane_lists
    - smarty
    - attr_list
    - footnotes
    - admonition
    - codehilite:
        guess_lang: true
        linenums: true
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tabbed
    - pymdownx.tilde
    
    
theme:
    favicon: images/logo.svg
    name: material
    logo: images/logo.svg
    language: en
    features:
        - instant
    palette:
        primary: green
    font: true
        
site_favicon: images/logo.svg
